### ISSUE TITLE
number_to_human skips some numbers

### ISSUE THREAD

**Issue by dmarkow** [danielberkompas/number#10]
```
iex(6)> Number.Human.number_to_human 998994
"998.99 Thousand"
iex(7)> Number.Human.number_to_human 998999
"998.00 Thousand"
iex(8)> Number.Human.number_to_human 999000
"999.00 Thousand"
iex(9)> Number.Human.number_to_human 999001
** (FunctionClauseError) no function clause matching in Number.Human.number_to_human/2
    lib/number/human.ex:47: Number.Human.number_to_human(999001, [])
```

1. The result for 998999 should be "998.99 thousand" not "999.00 thousand"? It looks like it's rounding the decimal portion (0.999) up (to 1.000) and then just using the .000 part (since 998,994 works correctly but 998,995-998,999 do not)?
2. 999,001 through 999,999 raise an error. Same with 999,000,001 through 999,999,999, etc. This is because the multiplier of 999 gives a max of 999,000 for 1,000, 999,000,000 for 1,000,000, etc.

I can look into this and possibly provide a pull request when I have some more time.

**Comment by danielberkompas** [comment]
Thanks for this report. I will look into it as soon as I can.
