### ISSUE TITLE
Module not available in releases if not listed in :applications

### ISSUE THREAD

**Issue by andrejsm** [danielberkompas/number#14]
Just ran in an issue where `Number` module was not available in umbrella project unless listed in `:applications`.

In `mix.exs` had to add:
```elixir
  def application do
    [mod: {MyApp, []},
     applications: [:number]
    ]
  end
```

Oh yes, releases are built with `exrm`

**Comment by danielberkompas** [comment]
It's normal to have to include each dependency in the `:applications` when building with ExRM. As far as I can tell, this isn't a bug with Number. Do you have any other details that indicate a bug?

**Comment by andrejsm** [comment]
Probably this should be mentioned in the readme
