### ISSUE TITLE
Add to application list in mix.exs?

### ISSUE THREAD

**Issue by railsmechanic** [danielberkompas/number#23]
The readme indicates that we need to "Make sure you also add it to your application list in mix.exs". Is this information correct, because it doesn't look like that **number** is an OTP application?

**Comment by danielberkompas** [comment]
You're correct that it isn't an OTP application, but it's still a good idea to add it to the `application` list. All dependencies have to be in the `applications` list in order for release managers like ExRM or Distillery to work properly.
