### ISSUE TITLE
Number formatting with abbreviations: $1,200,000 -> $1.2MM, $5,586 -> $5.6k, etc.

### ISSUE THREAD

**Issue by micahwedemeyer** [danielberkompas/number#26]
I'm just wondering if it's possible to use this package to round/convert to "business-y" numbers. I'd like to display larger values, often currency, and use the abbreviated forms.

I can easily round on my own (ie. 5586 -> 5.6 x 1000), but it would be great if there were a way to then get the abbreviation suffix (ie. "MM", "k", "B"?) I guess once I list them out, there's only those 3 (and therefore not that hard), but I'm still wondering if there's anything built-in.

**Comment by danielberkompas** [comment]
See `Number.Human.number_to_human/2`. The unit names aren't currently configurable, (which should be changed) but you can use it like this:

```elixir
count
|> number_to_human(precision: 1)
|> String.replace(" Thousand", "K")
|> String.replace(" Million", "M")
|> String.replace(" Billion", "B")
|> String.replace(" Trillion", "T")
|> String.replace(" Quadrillion", "Q")
```

**Comment by micahwedemeyer** [comment]
Sweet, this is great! 👍

**Comment by sn3p** [comment]
This would be a nice to have build in.
