### ISSUE TITLE
Changelog entry for 1.0.0

### ISSUE THREAD

**Issue by tonyc** [danielberkompas/number#41]
:wave: Hi Daniel!

Thanks for maintaining this library. I recently had to do an upgrade from 0.5.7 to 1.0.0, and noticed there wasn't a changelog entry specifically for 1.0.0 -- just "unreleased" -- so I wasn't super clear on what was unreleased vs in 1.0.0. It would be useful to have a specific entry in the CHANGELOG for it now that it's published. 

Thanks!

**Comment by danielberkompas** [comment]
Fixed! https://github.com/danielberkompas/number/blob/master/CHANGELOG.md

**Comment by tonyc** [comment]
Thank you!!!
